name: irohasu_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Misc
  after_layout: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.3.2
  injectable_generator: ^2.1.2

  # Linting
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
