name: irohasu_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter   

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.1.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local storage
  shared_preferences: ^2.1.2

  # Gen
  envied: ^0.3.0+3

  # Network
  dio: ^5.3.3

  # Function Programing
  fpdart: ^0.6.0

  # Discovering the state of the network
  connectivity_plus: ^5.0.1

  # Misc
  after_layout: ^1.2.0
  gap: ^3.0.1
  
  # Log file
  logger: ^2.0.2+1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dependency_overrides:
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  envied_generator: ^0.3.0+3

  # Linting
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
